/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentIndexRouteImport } from './routes/tournament/index'
import { Route as ArenaIndexRouteImport } from './routes/arena/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ArenaMatchIdRouteImport } from './routes/arena/$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentIndexRoute = TournamentIndexRouteImport.update({
  id: '/tournament/',
  path: '/tournament/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/arena/',
  path: '/arena/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaMatchIdRoute = ArenaMatchIdRouteImport.update({
  id: '/arena/$matchId',
  path: '/arena/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena/$matchId': typeof ArenaMatchIdRoute
  '/agents': typeof AgentsIndexRoute
  '/arena': typeof ArenaIndexRoute
  '/tournament': typeof TournamentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena/$matchId': typeof ArenaMatchIdRoute
  '/agents': typeof AgentsIndexRoute
  '/arena': typeof ArenaIndexRoute
  '/tournament': typeof TournamentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena/$matchId': typeof ArenaMatchIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/arena/': typeof ArenaIndexRoute
  '/tournament/': typeof TournamentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arena/$matchId' | '/agents' | '/arena' | '/tournament'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arena/$matchId' | '/agents' | '/arena' | '/tournament'
  id:
    | '__root__'
    | '/'
    | '/arena/$matchId'
    | '/agents/'
    | '/arena/'
    | '/tournament/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaMatchIdRoute: typeof ArenaMatchIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
  TournamentIndexRoute: typeof TournamentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/': {
      id: '/tournament/'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/': {
      id: '/arena/'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/$matchId': {
      id: '/arena/$matchId'
      path: '/arena/$matchId'
      fullPath: '/arena/$matchId'
      preLoaderRoute: typeof ArenaMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaMatchIdRoute: ArenaMatchIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ArenaIndexRoute: ArenaIndexRoute,
  TournamentIndexRoute: TournamentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
